version: '3.8'

services:
  mysql:
    image: mariadb
    container_name: "local-mariadb"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql

  # git-stats:
  #   image: node:20
  #   container_name: git-stats
  #   restart: always
  #   working_dir: /app
  #   volumes:
  #     - ../:/app
  #   command: sh -c 'npm run start'
  #   ports:
  #     - "5000:5000"  
